In [1]:
from jobspy import scrape_jobs

In [2]:
import pandas as pd

In [4]:
jobList = pd.read_csv('Data-Related_Job_Titles.csv')

In [5]:
jobList

      Data & Business Analytics Jobs
0                       Data Analyst
1                Senior Data Analyst
2                Junior Data Analyst
3                   SQL Data Analyst
4                     Data Scientist
..                               ...
57                   Data Consultant
58  Business Intelligence Consultant
59         Customer Insights Analyst
60           Behavioral Data Analyst
61           Data Operations Analyst

[62 rows x 1 columns]

In [7]:
for keyWord in jobList['Data & Business Analytics Jobs']:
    print(keyWord)

Data Analyst
Senior Data Analyst
Junior Data Analyst
SQL Data Analyst
Data Scientist
Senior Data Scientist
Machine Learning Engineer
Data Engineer
Big Data Engineer
Data Architect
Database Administrator
ETL Developer
Business Intelligence Analyst
BI Developer
Analytics Engineer
Business Analyst
IT Business Analyst
Financial Analyst
Marketing Analyst
Operations Analyst
Strategy Analyst
Product Analyst
Sales Analyst
Supply Chain Analyst
Revenue Analyst
Pricing Analyst
Commercial Analyst
Data Steward
Data Governance Analyst
Data Quality Analyst
Metadata Specialist
Data Management Specialist
Master Data Analyst
Tableau Developer
Power BI Developer
Data Visualization Specialist
Dashboard Developer
Reporting Analyst
Excel Analyst
NLP Engineer
AI Data Analyst
Risk Analyst
Quantitative Analyst
Credit Risk Analyst
Fraud Analyst
Actuarial Analyst
Cloud Data Engineer
AWS Data Engineer
Azure Data Analyst
Google Cloud Data Engineer
Snowflake Engineer
Databricks Engineer
Spark Developer
Hadoop Developer
Insights Analyst
Data Research Analyst
KPI Analyst
Data Consultant
Business Intelligence Consultant
Customer Insights Analyst
Behavioral Data Analyst
Data Operations Analyst

In [10]:
all_jobs = []
for keyWord in jobList['Data & Business Analytics Jobs']:
    jobs = scrape_jobs(
        site_name=["indeed"],
        search_term=keyWord,
        location="Canada",
        results_wanted=100,
        hours_old=200,
        country_indeed="canada" 
    )
    print(f"{keyWord}: Found {len(jobs)} jobs.")
    all_jobs.append(jobs)

Data Analyst: Found 100 jobs.
Senior Data Analyst: Found 100 jobs.
Junior Data Analyst: Found 93 jobs.
SQL Data Analyst: Found 100 jobs.
Data Scientist: Found 100 jobs.
Senior Data Scientist: Found 100 jobs.
Machine Learning Engineer: Found 100 jobs.
Data Engineer: Found 100 jobs.
Big Data Engineer: Found 100 jobs.
Data Architect: Found 100 jobs.
Database Administrator: Found 69 jobs.
ETL Developer: Found 44 jobs.
Business Intelligence Analyst: Found 100 jobs.
BI Developer: Found 53 jobs.
Analytics Engineer: Found 100 jobs.
Business Analyst: Found 100 jobs.
IT Business Analyst: Found 100 jobs.
Financial Analyst: Found 100 jobs.
Marketing Analyst: Found 100 jobs.
Operations Analyst: Found 100 jobs.
Strategy Analyst: Found 100 jobs.
Product Analyst: Found 100 jobs.
Sales Analyst: Found 100 jobs.
Supply Chain Analyst: Found 36 jobs.
Revenue Analyst: Found 100 jobs.
Pricing Analyst: Found 45 jobs.
Commercial Analyst: Found 100 jobs.
Data Steward: Found 100 jobs.
Data Governance Analyst: Found 100 jobs.
Data Quality Analyst: Found 100 jobs.
Metadata Specialist: Found 6 jobs.
Data Management Specialist: Found 100 jobs.
Master Data Analyst: Found 80 jobs.
Tableau Developer: Found 12 jobs.
Power BI Developer: Found 39 jobs.
Data Visualization Specialist: Found 28 jobs.
Dashboard Developer: Found 87 jobs.
Reporting Analyst: Found 100 jobs.
Excel Analyst: Found 100 jobs.
NLP Engineer: Found 19 jobs.
AI Data Analyst: Found 91 jobs.
Risk Analyst: Found 100 jobs.
Quantitative Analyst: Found 61 jobs.
Credit Risk Analyst: Found 79 jobs.
Fraud Analyst: Found 6 jobs.
Actuarial Analyst: Found 9 jobs.
Cloud Data Engineer: Found 55 jobs.
AWS Data Engineer: Found 3 jobs.
Azure Data Analyst: Found 97 jobs.
Google Cloud Data Engineer: Found 15 jobs.
Snowflake Engineer: Found 37 jobs.
Databricks Engineer: Found 44 jobs.
Spark Developer: Found 21 jobs.
Hadoop Developer: Found 9 jobs.
Insights Analyst: Found 100 jobs.
Data Research Analyst: Found 100 jobs.
KPI Analyst: Found 44 jobs.
Data Consultant: Found 100 jobs.
Business Intelligence Consultant: Found 66 jobs.
Customer Insights Analyst: Found 100 jobs.
Behavioral Data Analyst: Found 13 jobs.
Data Operations Analyst: Found 100 jobs.

In [11]:
combined_jobs = pd.concat(all_jobs, ignore_index=True)

In [13]:
combined_jobs

,id,site,job_url,job_url_direct,title,company,location,date_posted,job_type,salary_source,...,company_addresses,company_num_employees,company_revenue,company_description,skills,experience_range,company_rating,company_reviews_count,vacancy_count,work_from_home_type
0,in-04c33a22378444d2,indeed,https://ca.indeed.com/viewjob?jk=04c33a22378444d2,http://ca.indeed.com/job/operations-analyst-04...,Operations Analyst,North Atlantic (North Atlantic Marketing LP),"St. John's, NL, CA",2025-05-30,"temporary, fulltime",None,...,NaN,NaN,NaN,NaN,None,None,None,None,None,None
1,in-d9b9d1cc2964ce9a,indeed,https://ca.indeed.com/viewjob?jk=d9b9d1cc2964ce9a,https://mcgill.wd3.myworkdayjobs.com/en-US/mcg...,Course Lecturer - URBP 611 Data Visualization ...,McGill University,"Montréal, QC, CA",2025-05-30,parttime,None,...,845 Sherbrooke Street West\r\nMontréal (Québec...,"5,001 to 10,000",$1B to $5B (USD),NaN,None,None,None,None,None,None
2,in-e488344a57c20e0d,indeed,https://ca.indeed.com/viewjob?jk=e488344a57c20e0d,https://careers.metrovancouver.org/psc/CAREERS...,Operations Data Analyst,Metro Vancouver,"Burnaby, BC, CA",2025-05-30,fulltime,None,...,Burnaby,"1,001 to 5,000",$500M to $1B (USD),NaN,None,None,None,None,None,None
3,in-7eea9d56073acb5f,indeed,https://ca.indeed.com/viewjob?jk=7eea9d56073acb5f,https://Tangam.recruiterbox.com/jobs/fk0pccw?f...,Data Analyst,Tangam Systems,"Waterloo, ON, CA",2025-05-30,NaN,None,...,Waterloo,2 to 10,NaN,NaN,None,None,None,None,None,None
4,in-0dfe56744b91338a,indeed,https://ca.indeed.com/viewjob?jk=0dfe56744b91338a,https://careers-lspower.icims.com/jobs/1730/jo...,Data Resource Analyst,"LS Power Development, LLC","Oakville, ON, CA",2025-05-29,fulltime,None,...,NaN,NaN,NaN,NaN,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4556,in-a5de290dcda71aa2,indeed,https://ca.indeed.com/viewjob?jk=a5de290dcda71aa2,https://job-boards.greenhouse.io/flipp/jobs/66...,Financial Analyst,NaN,"Remote, CA",2025-05-28,NaN,None,...,NaN,NaN,NaN,NaN,None,None,None,None,None,None
4557,in-25d2b593c0749d3e,indeed,https://ca.indeed.com/viewjob?jk=25d2b593c0749d3e,https://paracellabs.applytojob.com/apply/svAfJ...,Asbestos Analyst,PARACEL LABORATORIES,"Mississauga, ON, CA",2025-05-28,fulltime,None,...,Ottawa,11 to 50,$1M to $5M (USD),NaN,None,None,None,None,None,None
4558,in-b8fe84db6f5aa6ab,indeed,https://ca.indeed.com/viewjob?jk=b8fe84db6f5aa6ab,https://miovision.applytojob.com/apply/fhGAZ5R...,"Senior Financial Analyst, FP&A",Miovision Technologies,"Remote, CA",2025-05-28,fulltime,None,...,"Kitchener, ON",201 to 500,$25M to $100M (USD),Miovision solutions can help improve mobility ...,None,None,None,None,None,None
4559,in-cb6c46d345a6482e,indeed,https://ca.indeed.com/viewjob?jk=cb6c46d345a6482e,https://jobs.scotiabank.com/job/Toronto-Manage...,"Manager, Compliance and AML Data / AML Governa...",Scotiabank,"Toronto, ON, CA",2025-05-24,NaN,None,...,"Toronto, ON","10,000+",more than $10B (USD),Scotiabank is a leading bank in the Americas a...,None,None,None,None,None,None
4560,in-efe563730a820c41,indeed,https://ca.indeed.com/viewjob?jk=efe563730a820c41,https://bmo.wd3.myworkdayjobs.com/en-US/Extern...,"Operations Analyst, Fall 2025 (Co-op/Internshi...",BMO Financial Group,"Barrie, ON, CA",2025-05-22,fulltime,None,...,"Toronto, ON","10,000+",more than $10B (USD),At BMO we are driven by a shared Purpose: Bold...,None,None,None,None,None,None

In [15]:
combined_jobs.to_csv("data_jobs_indeed.csv", index=False)